KerasJson: DC.json
KerasH5: DC.h5
InputData: SimData/input_c.dat
OutputPredictions: SimData/labels.dat
OutputDir: DC
ProjectName: DC
XilinxPart: xcvu9p-flgc2104-2-i
ClockPeriod: 5

IOType: io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 60000
    Strategy: Resource
